artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Phabi95/ml-project-end-to-end/raw/refs/heads/main/wine.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/wine/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt
